# Generated by Django 3.2.5 on 2021-09-08 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_file_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
